export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ADD_CANDIDATE_LOADING = "ADD_CANDIDATE_LOADING"
export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS"
export const ADD_CANDIDATE_FAIL = "ADD_CANDIDATE_FAIL"

export const GET_CANDIDATE_LOADING = "GET_CANDIDATE_LOADING"
export const GET_CANDIDATE_SUCCESS = "GET_CANDIDATE_SUCCESS"
export const GET_CANDIDATE_FAIL = "GET_CANDIDATE_FAIL"

export const UPDATE_CANDIDATE_STATUS_LOADING = "UPDATE_CANDIDATE_STATUS_LOADING";
export const UPDATE_CANDIDATE_STATUS_SUCCESS = "UPDATE_CANDIDATE_STATUS_SUCCESS";
export const UPDATE_CANDIDATE_STATUS_FAIL = "UPDATE_CANDIDATE_STATUS_FAIL";

export const DELETE_CANDIDATE_LOADING = "DELETE_CANDIDATE_LOADING";
export const DELETE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_FAIL = "DELETE_CANDIDATE_FAIL";

export const GET_VOTERS_LOADING = "GET_VOTERS_LOADING"
export const GET_VOTERS_SUCCESS = "GET_VOTERS_SUCCESS"
export const GET_VOTERS_FAIL = "GET_VOTERS_FAIL"

export const UPDATE_VOTERS_STATUS_LOADING = "UPDATE_VOTERS_STATUS_LOADING";
export const UPDATE_VOTERS_STATUS_SUCCESS = "UPDATE_VOTERS_STATUS_SUCCESS";
export const UPDATE_VOTERS_STATUS_FAIL = "UPDATE_VOTERS_STATUS_FAIL";

export const DELETE_VOTERS_LOADING = "DELETE_VOTERS_LOADING";
export const DELETE_VOTERS_SUCCESS = "DELETE_VOTERS_SUCCESS";
export const DELETE_VOTERS_FAIL = "DELETE_VOTERS_FAIL";