export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ADD_CANDIDATE_LOADING = "ADD_CANDIDATE_LOADING"
export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS"
export const ADD_CANDIDATE_FAIL = "ADD_CANDIDATE_FAIL"

export const GET_CANDIDATE_LOADING = "GET_CANDIDATE_LOADING"
export const GET_CANDIDATE_SUCCESS = "GET_CANDIDATE_SUCCESS"
export const GET_CANDIDATE_FAIL = "GET_CANDIDATE_FAIL"

export const UPDATE_CANDIDATE_STATUS_LOADING = "UPDATE_CANDIDATE_STATUS_LOADING";
export const UPDATE_CANDIDATE_STATUS_SUCCESS = "UPDATE_CANDIDATE_STATUS_SUCCESS";
export const UPDATE_CANDIDATE_STATUS_FAIL = "UPDATE_CANDIDATE_STATUS_FAIL";

export const DELETE_CANDIDATE_LOADING = "DELETE_CANDIDATE_LOADING";
export const DELETE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_FAIL = "DELETE_CANDIDATE_FAIL";

export const GET_VOTERS_LOADING = "GET_VOTERS_LOADING"
export const GET_VOTERS_SUCCESS = "GET_VOTERS_SUCCESS"
export const GET_VOTERS_FAIL = "GET_VOTERS_FAIL"

export const UPDATE_VOTERS_STATUS_LOADING = "UPDATE_VOTERS_STATUS_LOADING";
export const UPDATE_VOTERS_STATUS_SUCCESS = "UPDATE_VOTERS_STATUS_SUCCESS";
export const UPDATE_VOTERS_STATUS_FAIL = "UPDATE_VOTERS_STATUS_FAIL";

export const DELETE_VOTERS_LOADING = "DELETE_VOTERS_LOADING";
export const DELETE_VOTERS_SUCCESS = "DELETE_VOTERS_SUCCESS";
export const DELETE_VOTERS_FAIL = "DELETE_VOTERS_FAIL";

export const START_END_VOTING_LOADING = "START_END_VOTING_LOADING";
export const START_END_VOTING_SUCCESS = "START_END_VOTING_SUCCESS";
export const START_END_VOTING_FAIL = "START_END_VOTING_FAIL";

export const IS_VOTING_START_LOADING = "IS_VOTING_START_LOADING";
export const IS_VOTING_START_SUCCESS = "IS_VOTING_START_SUCCESS";
export const IS_VOTING_START_FAIL = "IS_VOTING_START_FAIL";

export const CANDIDATE_LOADING = "CANDIDATE_LOADING";
export const CANDIDATE_SUCCESS = "CANDIDATE_SUCCESS";
export const CANDIDATE_FAIL = "CANDIDATE_FAIL";

export const ADMIN_RESULT_LOADING = "ADMIN_RESULT_LOADING";
export const ADMIN_RESULT_SUCCESS = "ADMIN_RESULT_SUCCESS";
export const ADMIN_RESULT_FAIL = "ADMIN_RESULT_FAIL";

export const USER_RESULT_LOADING = "USER_RESULT_LOADING";
export const USER_RESULT_SUCCESS = "USER_RESULT_SUCCESS";
export const USER_RESULT_FAIL = "USER_RESULT_FAIL";

export const CAST_VOTE_LOADING = "CAST_VOTE_LOADING";
export const CAST_VOTE_SUCCESS = "CAST_VOTE_SUCCESS";
export const CAST_VOTE_FAIL = "CAST_VOTE_FAIL";