export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const ADD_CANDIDATE_LOADING = "ADD_CANDIDATE_LOADING"
export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS"
export const ADD_CANDIDATE_FAIL = "ADD_CANDIDATE_FAIL"